<?php
get_header();
get_template_part('template/homepage/section1');
get_template_part('template/homepage/section2');
get_template_part('template/homepage/section3');
get_template_part('template/homepage/section4');
get_template_part('template/homepage/section5');
get_template_part('template/homepage/section6');
get_footer();
?>
